### ISSUE TITLE
Should I have to run the docker-osx-dev command whenever I lose connection?

### ISSUE THREAD

**Issue by sanchezjjose** [brikis98/docker-osx-dev#115]
It seems like the file watching and rsync process go stale after a while, and I need to often restart the process to start syncing files again in order to get the application startup speed benefits. 

Also, each time I restart it, I see the following messages, and I have to select yes each time:

2015-09-29 12:01:06 [ERROR] Found VirtualBox shared folders on your Boot2Docker VM. These may void any performance benefits from using docker-osx-dev:
/Users
2015-09-29 12:01:06 [INSTRUCTIONS] Would you like this script to remove them?

**Comment by brikis98** [comment]
I haven't seen any issue with staleness. It's just a local filewatcher and it runs rsync afresh every time there is a change, so there is no open connection or anything to be lost.

That said, if you're getting warnings about VirtualBox shared folders, that may mean you're not using docker-osx-dev at all and all the syncing is handle by the (very slow) VirtualBox mechanism. You can unmount those shared folders or just delete your boot2docker image and allow docker-osx-dev to recreate it.

**Comment by sanchezjjose** [comment]
I actually don't have boot2docker installed, I use Kitematic, because I installed with the latest docker toolbox, so the VM being used is called default. I run the command like this:

docker-osx-dev -m default -s /path/to/app

Is this the correct usage, and should I delete the default VM created by the Docker Toolbox, and docker-osx-dev would recreate it?

Thanks for your help.

**Comment by sanchezjjose** [comment]
I allowed docker-osx-dev to recreate it, and seems fine right now, however I will still continue to use the -m default option, since all my docker images are installed on a separate docker-machine. Closing the issue for now, thanks!
