### ISSUE TITLE
El Capitan spoiled performance

### ISSUE THREAD

**Issue by ain** [brikis98/docker-osx-dev#119]
I'm experiencing severe performance issues on El Capitan. Not sure where they came from, but it looks like docker-osx-dev has no impact anymore. What's the best way to debug?

VBoxHeadless runs at full wack on CPU, also something that wasn't happening before.

**Comment by DanyC97** [comment]
i bet this has s'thing to do with Vbox, suggest to fire an email on VirtualBox forum too

**Comment by ain** [comment]
Correct, resolved by reinstalling VirtualBox.
