### ISSUE TITLE
Can we make exclude .git optional?

### ISSUE THREAD

**Issue by joannbrereton** [brikis98/docker-osx-dev#121]
The exclude of .git directory breaks any docker git and by extension bower updates when run in docker.  Is there any way we can make that exclude line optional?   Yeah, I can fork this but wondering what the rationale is for exclusion in the first place.

**Comment by brikis98** [comment]
Run docker-osx-dev with the `-h` flag and you'll see there are several ways to customize excludes.

**Comment by joannbrereton** [comment]
Super, thanks!  Go ahead and close this.

**Comment by joannbrereton** [comment]
Sorry, I'm still a little dense here.

So,  I don't want to exclude anything from my home directory.   I've tried using an empty .dockerignore file and tried to specify --exclude with nothing after it.  Neither seems to work.  I still get .git on the exclude list. 

How do I include all subdirectories and file and exclude nothing?

The only way I could find to do this was to create a dummy directory and use the --exclude option using that dummy directory name. That seems a little convoluted.   Is there a better way?
