### ISSUE TITLE
ssh into docker-osx-dev vm

### ISSUE THREAD

**Issue by theverything** [brikis98/docker-osx-dev#13]
I am trying to ssh into the vm in order to add the `--insecure-registry` flag to the docker daemon. We us a private registry behind our firewall.

I tried running `ssh localdocker` which prompts me to add localdocker to knownhosts, but then it requires a password (which I don't know).

Am I going about it the wrong way?

**Comment by brikis98** [comment]
Ah, yes, since docker-osx-dev uses vagrant under the hood, you should use `vagrant ssh`.

**Comment by brikis98** [comment]
Closing the issue. Please re-open if you're still having problems.
