### ISSUE TITLE
Relaxed HomeBrew requirement

### ISSUE THREAD

**Issue by ain** [brikis98/docker-osx-dev#137]
When I don't have HomeBrew, but dependencies are met, I'm still having problems running it due to a (non-critical?) dependency check:

```
2015-11-11 17:03:25 [ERROR] This script requires HomeBrew, but it's not installed. Aborting.
```

I'd propose relaxing the HomeBrew requirement and applying the check only in the install call.

**Comment by brikis98** [comment]
Seems like a reasonable improvement. The check would need to be removed from `check_prerequisites` and the `brew_install` function would have to be updated to search for the `command` on the `PATH` first, and if that's not found, and `brew` isn't installed, it should error out saying something like "Required dependency XXX could not be found and HomeBrew is not available to install it".
