### ISSUE TITLE
changes in mounted container directory not being synced back to host directory

### ISSUE THREAD

**Issue by skomputer** [brikis98/docker-osx-dev#14]
I create a container with `-v /host/path:/container/path` to mount a directory.

Changes to `/container/path` in my container are not synced back to `/host/path` on my host machine.

However, changes to `/host/path` are synced to `/container/path`.

**Comment by brikis98** [comment]
Sorry about that, but it is one of the limitations of rsync, as listed in [the limitations section of the readme](https://github.com/brikis98/docker-osx-dev#limitations-and-known-issues).
