### ISSUE TITLE
Installing rsync on docker host behind a proxy

### ISSUE THREAD

**Issue by marzolfb** [brikis98/docker-osx-dev#141]
Ran into this:

```
2015-11-13 08:28:58 [INFO] Installing rsync in the Docker Host image
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: download timed out
md5sum: rsync.tcz.md5.txt: No such file or directory
Error on rsync.tcz
exit status 1
exit status 127
2015-11-13 08:29:44 [INFO] Failed to install rsync using tce-load, falling back to install rsync from pre-built binary in docker-osx-dev GitHub repo
Connecting to raw.githubusercontent.com (199.27.76.133:443)
wget: error getting response: Connection reset by peer
exit status 1
```

I worked around it by changing this line:

```
  if ! $DOCKER_HOST_SSH_COMMAND "if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi"; then
```

to this:

```
  if ! $DOCKER_HOST_SSH_COMMAND "if ! type rsync > /dev/null 2>&1; then http_proxy='http://myproxyuser:myproxypassword@myproxyaddress:myproxyport/' tce-load -wi rsync; fi"; then
```

**Comment by brikis98** [comment]
Do you know if a lot of developers are likely to be behind a similar proxy? If so, I'd be happy to accept a PR to add a proxy parameter and pass it through to the rsync install. If it's a fairly uncommon thing, then at least with this bug filed, other developers who hit this will be able to find a workaround.

**Comment by ain** [comment]
PR could be there anyway, but IMHO, it's not really something that is common. Working behind the proxy for any developer is generally painful and something to avoid.

**Comment by marzolfb** [comment]
I haven't seen any data on proxy usage so its hard to say whether its commonplace (I would guess it isn't). Feel free to close. Like you said @brikis98, the next person that comes along will hopefully be aided by my workaround.

**Comment by brikis98** [comment]
@marzolfb Thanks for the info. I'll close this issue for now. 

If anyone else hits this problem, please add a comment. If it turns out to be more common than we expected, we can reopen and fix it.
