### ISSUE TITLE
Cask is no longer installed with 'brew install' but rather with 'brew tap'

### ISSUE THREAD

**Issue by ellismarkf** [brikis98/docker-osx-dev#162]
https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system

Cask has apparently updated it's install and update method and no longer relies on `brew install` to install or update.  I'm not totally sure why this change would break the docker-osx-dev install script, but I get the following error when trying to run `docker-osx-dev install`:

==> Installing brew-cask from caskroom/cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
==> Checking out tag v0.60.0
==> Caveats
You can uninstall this formula as `brew tap Caskroom/cask` is now all that's
needed to install Homebrew Cask and keep it up to date.
==> Summary
🍺  /usr/local/Cellar/brew-cask/0.60.0: 3 files, 5K, built in 2 seconds
2016-01-05 15:04:17 [ERROR] Failed to install dependency Cask. Check the log output above for reasons.

Running `brew list` after `docker-osx-dev install` fails shows that brew-cask was indeed installed, but perhaps the caveat returns a different code than a straight successful install would?

I'm not an expert in Homebrew, Cask, or shell scripting, but if Cask is installed via `brew tap`, the path to caskroom would be different, which would mean that the manual check to see if dependencies were successfully installed in the docker-osx-dev script would always fail, correct?  Is there some other solution that I'm just naively overlooking?

Thanks for the help!

**Comment by ellismarkf** [comment]
To clarify, running `docker-osx-dev install` a second time completes successfully (since brew-case was actually installed), but it seems like the script should run successfully the first time.

**Comment by brikis98** [comment]
Thanks for filing! We should definitely update the code to use `tap`.

**Comment by brikis98** [comment]
Anyone interested in submitting a PR to fix this issue? I'm a bit overloaded at the moment.

**Comment by ain** [comment]
I'm calling for disbanding support for dependency installation to the extent that overlaps with Docker Toolbox. 

We should only take care of dependencies that are necessary for `docker-osx-dev` functionality.
