### ISSUE TITLE
Question about available docker images and multiple projects/folders

### ISSUE THREAD

**Issue by pschneider** [brikis98/docker-osx-dev#17]
Hi,

your project looks awesome so far! I really like it.

Just one problem I ran into:

I have some docker images which I've build for myself. I use these images as a base for nearly every project I have. With docker-osx-dev I have the problem, that a docker image is available globally due to the fact that the VM is different for every folder and I need to build these images every time I start a new project.

Wouldn't it be better to share a VM for every docker-osx-dev project so that downloaded/custom build Images are available everywhere? You can't start multiple ones anyways. At least not without changing the Port in your Vagrantfile. 

Greetings

**Comment by brikis98** [comment]
You could have a single vagrant project for everything, but you'd need to run docker-osx-dev from a root folder that contains all of your projects. For example, consider this directory structure:

```
~/my-source-code
  └ project1
  └ project2
  └ project3
```

If you run `docker-osx-dev init` and `docker-osx-dev start` inside of `~/my-source-code`, then you'll be able to build and run docker containers in `project1`, `project2`, and `project3` all on the same boot2docker image. 

The only gotcha is that docker-osx-dev uses rsync to sync files to the VM. If `~/my-source-code` has a lot of files, this might cause performance issues (e.g., `docker-osx-dev start` takes a lot longer and you run out of file watchers locally). That said, you could try it out and see how well it works. You could also modify the `DEFAULT_FOLDERS_TO_SYNC` variable in the `Vagrantfile` created by `docker-osx-dev init` to be more picky on exactly which folders under `~/my-source-code` gets synced, or even submit a PR that makes this a configurable setting via command line params or a config file.

**Comment by pschneider** [comment]
Thanks for your suggestion. I will try this to see how the performance is and maybe I'll get the sync of a specific folder working via a command line parameter.

**Comment by brikis98** [comment]
I just updated the docker-osx-dev project to remove the Vagrant dependency. It's now just rsync + Boot2Docker and you should be able to use the same VM with multiple folders without issue. Check out the latest README and let me know if it works for you!

**Comment by brikis98** [comment]
Update: just tested the new docker-osx-dev with several projects at the same time, and it works fine. Example:

```
> cd /project1
> docker-osx-dev
> docker run -v /project1:/project1 project1-image

> cd /project2
> docker-osx-dev
> docker run -v /project2:/project2 project2-image
```

The files for both `/project1` and `/project2` are now being synced to the same Boot2Docker VM, so all of your Docker downloaded/built Docker images can be shared when you use `docker run`. I'm going to close this issue, but if you're still having trouble, reopen it.

**Comment by pschneider** [comment]
Works fine now. Thank you!
