### ISSUE TITLE
Support for ignored path/pattern in vm

### ISSUE THREAD

**Issue by otbe** [brikis98/docker-osx-dev#172]
Hi everybody,

is there any possibility to add paths or patterns that will be ignored by rsync on the container side?
`$ docker-osx-dev -i or -e` did not work for me, because the folder to ignore is not on source side.

Why? Im doing the following things:
- start build-tool-contianer for web apps (folder of web app is a volume)
- build web app (this step creates several folders...tmp, dist)
- browser-sync reloads my local browser

This works as expected, but Im seeing some errors in the output of `docker-osx-dev`

```
2016-02-15 18:14:37 [INFO] rsync: delete_file: unlink(app/dist/<filePath>) failed: Permission denied (13)
```

This is because the dist/ folder is not within my local web app folder, so rsync tries to delete it within the container/vm. This fails because of some permission problems. Any opinions?

Thank you.

**Comment by brikis98** [comment]
Can you provide more detail on why `-i` or `-e` don't work for you?

**Comment by otbe** [comment]
Shame on me.
For simple use I passed .gitignore to `-e`. The entries within my .gitignore were messed up a litte bit.
For example `/dist/` instead of `dist/`.

Works like expected. Thank you

**Comment by brikis98** [comment]
Good to hear.
