### ISSUE TITLE
rsync --exclude

### ISSUE THREAD

**Issue by bkcummins** [brikis98/docker-osx-dev#177]
we don't have a need to copy build tools such as node_modules and bower_components into the container.  has anyone thought about populating the rsync --exclude option with contents of something like .docker-osx-dev-ignore?

**Comment by brikis98** [comment]
Options for excluding individual files and using an exclude file (`.dockerignore`, by default) already exist. Run `docker-osx-dev --help`.

**Comment by bkcummins** [comment]
doh...missed the obvious.  thx!
