### ISSUE TITLE
case issue with Caskroom

### ISSUE THREAD

**Issue by jnoleau** [brikis98/docker-osx-dev#181]
https://github.com/brikis98/docker-osx-dev/blob/master/src/docker-osx-dev#L739

The result is : 

```
Error: Tap caskroom/cask remote mismatch.
https://github.com/caskroom/homebrew-cask != https://github.com/Caskroom/homebrew-cask
```

`brew tap Caskroom/cask` > `brew tap caskroom/cask` seems to work

**Comment by brikis98** [comment]
Ah, Cask has had a fair number of changes recently, so this must be one of them. Do you have any interest in submitting a one-character PR? :)

**Comment by jnoleau** [comment]
done (yes for testing purpose (this is my first PR on a public project) ^^)

PS : 

instead of docker-compose & docker-machine from brew I use dockertoolbox (containing compose, machine, boot2docker iso, kitematic)  from cask in my project, I don't know if it is interesting for this tool 

`brew_install "dockertoolbox" "docker-machine" "docker-machine" true`

**Comment by brikis98** [comment]
Thanks for the PR! It's now merged.

Using docker toolbox is something we've discussed before (#132) and would be worth another PR.
