### ISSUE TITLE
The vagrant plugin 'gatling-rsync' does not sync the files

### ISSUE THREAD

**Issue by Simperfit** [brikis98/docker-osx-dev#24]
Greets,

We were trying to use this to deploy development environment in our enterprise

But we find out that without using the command "docker-osx-dev  start-sync" when I change a file it does not sync.

When starting the project we use this process : 

docker-osx-dev start : output
[INFO] Starting Docker and Vagrant
Bringing machine 'boot2docker' up with 'virtualbox' provider...
==> boot2docker: Clearing any previously set forwarded ports...
==> boot2docker: Fixed port collision for 22 => 2222. Now on port 2200.
==> boot2docker: Clearing any previously set network interfaces...
==> boot2docker: Preparing network interfaces based on configuration...
    boot2docker: Adapter 1: nat
    boot2docker: Adapter 2: hostonly
==> boot2docker: Forwarding ports...
    boot2docker: 2375 => 2375 (adapter 1)
    boot2docker: 2376 => 2376 (adapter 1)
    boot2docker: 22 => 2200 (adapter 1)
==> boot2docker: Running 'pre-boot' VM customizations...
==> boot2docker: Booting VM...
==> boot2docker: Waiting for machine to boot. This may take a few minutes...
    boot2docker: SSH address: 127.0.0.1:2200
    boot2docker: SSH username: docker
    boot2docker: SSH auth method: private key
    boot2docker: Warning: Connection timeout. Retrying...
==> boot2docker: Machine booted and ready!
==> boot2docker: Checking for guest additions in VM...
==> boot2docker: Configuring and enabling network interfaces...
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/typo3conf/ => /Users/hamza/projet/project/typo3conf
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/uploads/ => /Users/hamza/projet/project/uploads
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/fileadmin/ => /Users/hamza/projet/project/fileadmin
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/typo3temp/ => /Users/hamza/projet/project/typo3temp
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/poject/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/dockerdata/mysql/ => /Users/hamza/projet/project/dockerdata/mysql
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin//", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Mounting shared folders...
    boot2docker: /vagrant => /Users/hamza/projet/project
==> boot2docker: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> boot2docker: to force provisioning. Provisioners marked to run always will still run.
[INFO] Starting file syncing

docker-compose up :
Recreating project_db_1...
Recreating project_web_1...
Attaching to project_db_1, project_web_1
db_1  | 150526  6:54:57 [Note] Plugin 'FEDERATED' is disabled.
db_1  | 150526  6:54:57  InnoDB: Initializing buffer pool, size = 8.0M
db_1  | 150526  6:54:57  InnoDB: Completed initialization of buffer pool
db_1  | InnoDB: The log sequence number in ibdata files does not match
db_1  | InnoDB: the log sequence number in the ib_logfiles!
db_1  | 150526  6:54:57  InnoDB: Database was not shut down normally!
db_1  | InnoDB: Starting crash recovery.
db_1  | InnoDB: Reading tablespace information from the .ibd files...
db_1  | InnoDB: Restoring possible half-written data pages from the doublewrite
db_1  | InnoDB: buffer...
db_1  | 150526  6:54:57  InnoDB: Started; log sequence number 0 859185403
db_1  | 150526  6:54:57 [Note] Event Scheduler: Loaded 0 events
db_1  | 150526  6:54:57 [Note] mysqld: ready for connections.
db_1  | Version: '5.1.73'  socket: '/tmp/mysql.sock'  port: 3306  MySQL Community Server (GPL)

At this point everything is going except for the syncing.

I'm on a mac mini  OSX 10.10.1

Docker version:

docker -v
Docker version 1.6.0, build 4749651

vagrant -v 
Vagrant 1.7.2

**Comment by brikis98** [comment]
Looks like you're using docker-compose. What is in your `docker-compose.yml` file?

**Comment by Simperfit** [comment]
here is it : 

web:
  image: gorghoa/typo3:6.2
  command: php -S 0.0.0.0:9999
  volumes:
    - typo3conf:/usr/src/typo3conf
    - uploads:/usr/src/uploads
    - fileadmin:/usr/src/fileadmin
    - typo3temp:/usr/src/typo3temp
  links:
    - db
  ports:
    - "9999:9999"

db:
  image: mtirsel/mysql-5.1
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - dockerdata/mysql:/var/lib/mysql
  ports:
    - "3311:3306"

we are using typo3.org (6.2 LTS)

**Comment by brikis98** [comment]
Let's try to get some more logging output. First, shut things down:

```
> docker-compose stop
> docker-osx-dev stop
```

Next, start things up manually:

```
> vagrant up
> vagrant gatling-rsync-auto
```

The last command should write the rsync progress to stdout. Finally, in a separate shell, fire up your Docker containers again:

```
> docker-compose up
```

Make some changes in OS X and let me know what the shell with `vagrant gatling-rsync-auto` running shows you.

**Comment by Simperfit** [comment]
vagrant up

Bringing machine 'boot2docker' up with 'virtualbox' provider...
==> boot2docker: Resuming suspended VM...
==> boot2docker: Booting VM...
==> boot2docker: Waiting for machine to boot. This may take a few minutes...
    boot2docker: SSH address: 127.0.0.1:2200
    boot2docker: SSH username: docker
    boot2docker: SSH auth method: private key
==> boot2docker: Machine booted and ready!

nymeria:project (master=)$ vagrant gatling-rsync-auto

==> boot2docker: Doing an initial rsync...
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/typo3conf/ => /Users/hamza/projet/project/typo3conf
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/uploads/ => /Users/hamza/projet/project/uploads
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/fileadmin/ => /Users/hamza/projet/project/fileadmin
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/typo3temp/ => /Users/hamza/projet/project/typo3temp
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Rsyncing folder: /Users/hamza/projet/project/dockerdata/mysql/ => /Users/hamza/projet/project/dockerdata/mysql
==> boot2docker:   - Exclude: [".vagrant/", "fileadmin/_", "!fileadmin/project/", "!fileadmin/templates/", "typo3conf/localconf.php", "typo3conf/ENABLE_INSTALL_TOOL", "typo3conf/temp_CACHED__", "typo3conf/l10n", "typo3conf/_.log", "typo3_src", "typo3", "INSTALL.txt", "phpinfo.php", "README.txt", "RELEASE_NOTES.txt", "._.DS_Store", ".__", ".htaccess", "dump/", "purge/", "uploads/", "/nbproject/private/", ".DS_Store", "typo3temp", "dockerdata"]
==> boot2docker: Watching: /Users/hamza/projet/project/dockerdata/mysql
==> boot2docker: Watching: /Users/hamza/projet/project/fileadmin
==> boot2docker: Watching: /Users/hamza/projet/project/typo3conf
==> boot2docker: Watching: /Users/hamza/projet/project/typo3temp
==> boot2docker: Watching: /Users/hamza/projet/project/uploads

docker-compose up
in the other shell : 
Recreating project_db_1...
Recreating project_web_1...
Attaching to project_db_1, project_web_1
db_1  | 150526  7:35:10 [Note] Plugin 'FEDERATED' is disabled.
db_1  | 150526  7:35:10  InnoDB: Initializing buffer pool, size = 8.0M
db_1  | 150526  7:35:10  InnoDB: Completed initialization of buffer pool
db_1  | InnoDB: The log sequence number in ibdata files does not match
db_1  | InnoDB: the log sequence number in the ib_logfiles!
db_1  | 150526  7:35:10  InnoDB: Database was not shut down normally!
db_1  | InnoDB: Starting crash recovery.
db_1  | InnoDB: Reading tablespace information from the .ibd files...
db_1  | InnoDB: Restoring possible half-written data pages from the doublewrite
db_1  | InnoDB: buffer...
db_1  | 150526  7:35:10  InnoDB: Started; log sequence number 0 859185403
db_1  | 150526  7:35:10 [Note] Event Scheduler: Loaded 0 events
db_1  | 150526  7:35:10 [Note] mysqld: ready for connections.
db_1  | Version: '5.1.73'  socket: '/tmp/mysql.sock'  port: 3306  MySQL Community Server (GPL)
Nothing other is showing in the shell than the 'Watching" part.

I've changed 2 files in /Users/hamza/projet/project/typo3conf/ but nothing is happening.

**Comment by brikis98** [comment]
Hmm, that's really bizarre. At this point, you're largely using the gatling-rsync plugin directly, so perhaps it has some bug or incompatibility I'm not seeing. Is the `Vagrantfile` unchanged from the one created by `boot2docker init`?

One other thought: I just released a new version of docker-osx-dev that no longer uses Vagrant or the gatling-rsync plugin. Instead, it just rsyncs directly to the Boot2Docker VM. It also has better logging to see what's going on. If we can't spot anything odd about the old version, you could try out the new version. See the [README](https://github.com/brikis98/docker-osx-dev) for the latest install/usage instructions and the [changelog](https://github.com/brikis98/docker-osx-dev#changelog) for how to remove the Vagrant stuff from the previous version.

**Comment by Simperfit** [comment]
The Vagrantfile is unchanged

I will try the new version and let you know.

**Comment by Simperfit** [comment]
The new setup does not install the docker-osx-dev script, (i've deleted the old version and i've deleted the vagrant file)

**Comment by Simperfit** [comment]
with the output of the install command, it may be better :) 

 curl https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/setup.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13690  100 13690    0     0  57828      0 --:--:-- --:--:-- --:--:-- 58008
[INFO] Updating HomeBrew
Already up-to-date.
[WARN] Cask is already installed by HomeBrew, skipping
[WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
[WARN] Found command boot2docker, assuming Boot2Docker is already installed and skipping
[WARN] Found command docker-compose, assuming Docker Compose is already installed and skipping
[WARN] fswatch is already installed by HomeBrew, skipping
[WARN] GNU core utilities is already installed by HomeBrew, skipping
[INFO] Starting Boot2Docker VM
Waiting for VM and Docker daemon to start...
.o
Started.
Writing /Users/hamza/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/hamza/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/hamza/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

[INFO] Installing rsync in the Boot2Docker image

**Comment by Simperfit** [comment]
It's working with the news version,

I've installed the script manually.

We have another question : 
How do you persiste the Databases modification (like Mysql) ?

**Comment by brikis98** [comment]
Great to hear it's working. Sorry about the upgrade process, versioned releases are still a TODO (see #23). I'm going to close this issue.

For databases, Docker usually recommends you store their data in a [data volume container](https://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container) which you keep around, even while the other containers (e.g. the DB code itself) get upgraded.
