### ISSUE TITLE
How should I use .dockerignore with node_modules?

### ISSUE THREAD

**Issue by noahsw** [brikis98/docker-osx-dev#30]
I tried running `(cd src/webapp; docker-osx-dev -i .dockerignore)` so that I wouldn't have to rsync massive folders like `node_modules`. You can see my `.dockerignore` at https://github.com/league-wins-pool/league-wins-pool/blob/develop/src/webapp/.dockerignore

The problem is once my containers run, the `node_modules` folder is not present (presumably because it's in my `.dockerignore`) and Node starts complaining about missing modules.

I suppose the ideal situation is one in which `node_modules` _is_ mapped into the container, but then not monitored for changes. Or use the `node_modules` folder that is built into the container instead of removing it when I map my local source folder. I hope that makes sense.

What do you suggest?

```
╰─± docker-osx-dev -l DEBUG
[DEBUG] Using default sync paths: .
[INFO] Using excludes from ignore file .dockerignore: .git .tmp .sass-cache bower_components dist node_modules .dockerignore
[INFO] Performing initial sync of paths: /Users/noah/Projects/league-wins-pool/src/webapp
[DEBUG] Creating parent directories in Docker VM: sudo mkdir -p /Users/noah/Projects/league-wins-pool/src && sudo chown -R docker /Users/noah/Projects/league-wins-pool/src
[DEBUG] rsync --archive --verbose --delete --omit-dir-times --inplace --whole-file --exclude .git --exclude .tmp --exclude .sass-cache --exclude bower_components --exclude dist --exclude node_modules --exclude .dockerignore --rsh="ssh -i /Users/noah/.ssh/id_boot2docker -o StrictHostKeyChecking=no" /Users/noah/Projects/league-wins-pool/src/webapp docker@dockerhost:/Users/noah/Projects/league-wins-pool/src
[INFO] Warning: Permanently added 'dockerhost,192.168.59.104' (RSA) to the list of known hosts.
[INFO] building file list ... done
[INFO]
[INFO] sent 2631 bytes  received 20 bytes  5302.00 bytes/sec
[INFO] total size is 347403  speedup is 131.05
[INFO] Initial sync done
[INFO] Watching: /Users/noah/Projects/league-wins-pool/src/webapp
[DEBUG] fswatch -0 --exclude .git --exclude .tmp --exclude .sass-cache --exclude bower_components --exclude dist --exclude node_modules --exclude .dockerignore /Users/noah/Projects/league-wins-pool/src/webapp
```

**Comment by brikis98** [comment]
This is actually a general problem with Docker and mounted volumes. Normally, you don't check the `node_modules` folder into source control, so when you check it out onto your host machine, it won't be there. If you then mount the source code from the host machine into a Docker container (whether with vboxsf or rsync), you won't be able to run the app right away until you run `npm install`.

I'm not sure what is the "idiomatic" solution, if there even is one, but what I do with my node apps is use `npm start` instead of directly calling `node server.js`. This allows me to define the commands used to run the app inside of `package.json` as follows:

``` js
{
  "name": "my-node-app",
  "dependencies": {
    "foo": "0.0.1"
  },
  "scripts": {
    "prestart": "if [ ! -d node_modules ]; then npm install; fi",
    "start": "node server.js"
  } 
}
```

This will run `npm install` inside the container the first time you run the app and as long as `node_modules` is in your `.dockerignore`, rsync will _not_ delete it.

**Comment by noahsw** [comment]
Ah - the mess continues ;-)

I started to play with this but it seems like some packages within `npm install` don't like running under the node context. Is it possible they require `sudo`?

```
webapp_1 |
webapp_1 | > server@0.4.0 test /webapp/server
webapp_1 | > npm install && NODE_ENV=development nodemon ./bin/www
webapp_1 |
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/cookie-parser/1.3.4/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/serve-favicon/2.2.0/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/morgan/1.5.2/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/babel/5.3.1/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/body-parser/1.12.2/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/mysql/2.6.2/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/sequelize/2.0.6/package.tgz
webapp_1 | npm ERR! tar.unpack untar error /root/.npm/express/4.12.3/package.tgz
webapp_1 | npm ERR! Linux 3.18.11-tinycore64
webapp_1 | npm ERR! argv "node" "/usr/local/bin/npm" "install"
webapp_1 | npm ERR! node v0.12.2
webapp_1 | npm ERR! npm  v2.9.1
webapp_1 | npm ERR! path /webapp/server/node_modules/cookie-parser/package.json
webapp_1 | npm ERR! code EPERM
webapp_1 | npm ERR! errno -1
webapp_1 |
webapp_1 | npm ERR! Error: EPERM, chown '/webapp/server/node_modules/cookie-parser/package.json'
webapp_1 | npm ERR!     at Error (native)
webapp_1 | npm ERR!  { [Error: EPERM, chown '/webapp/server/node_modules/cookie-parser/package.json']
webapp_1 | npm ERR!   errno: -1,
webapp_1 | npm ERR!   code: 'EPERM',
webapp_1 | npm ERR!   path: '/webapp/server/node_modules/cookie-parser/package.json',
webapp_1 | npm ERR!   fstream_finish_call: 'chown',
webapp_1 | npm ERR!   fstream_type: 'File',
webapp_1 | npm ERR!   fstream_path: '/webapp/server/node_modules/cookie-parser/package.json',
webapp_1 | npm ERR!   fstream_class: 'FileWriter',
webapp_1 | npm ERR!   fstream_stack:
webapp_1 | npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:308:19',
webapp_1 | npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:143:7',
webapp_1 | npm ERR!      'FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)' ] }
webapp_1 | npm ERR!
webapp_1 | npm ERR! Please try running this command again as root/Administrator.
webapp_1 |
webapp_1 | npm ERR! Please include the following file with any support request:
webapp_1 | npm ERR!     /webapp/server/npm-debug.log
webapp_1 | npm ERR! Test failed.  See above for more details.
src_webapp_1 exited with code 1
```

I really appreciate the help @brikis98 !

**Comment by brikis98** [comment]
Looks like a `chown` error. Perhaps you don't have permissions in that directory? What user are you using in the container, what folder are you putting the code into, and who is the owner on it?

**Comment by noahsw** [comment]
I simply deleted `src/webapp/server/node_modules` from my local machine and now it worked. Although I didn't delete `src/webapp/client/node_modules` and that's working too.

The only major change I made was to move `npm install` to `preinstall` like you said. In my example above, I shoehorned it into `npm test`. I don't see how that would have had an impact but maybe it did.

Glory!
