### ISSUE TITLE
Rsync disappear when rebooting the boot2docker VM.

### ISSUE THREAD

**Issue by Simperfit** [brikis98/docker-osx-dev#35]
Hi there,

We have been notified of a bug since the last version you released,

In order to get docker-osx-dev working we have to do the following : 

boot2docker start --vbox-share=disable
boot2docker ssh
tce (then s, rsync i)

Then it works like a charm.

**Comment by brikis98** [comment]
I'm not sure I follow. Were you getting some sort of error? What is "tce (then s, rsync i)"?

**Comment by Simperfit** [comment]
We have to install rsync with tce directly in the VM each time we boot it.
The rsync install is not persisted to the boot2docker machine.

**Comment by brikis98** [comment]
It's not persisted after what? After a reboot?

**Comment by Simperfit** [comment]
Yes, after a reboot.

**Comment by brikis98** [comment]
Heh, I guess I haven't rebooted my computer in a long time and didn't even think about it :) Thanks for reporting.

Probably the right solution is to move the boot2docker init logic from `setup.sh` to the `docker-osx-dev` script.

**Comment by Simperfit** [comment]
I will try to do it, do you want it to be really moved ? 

I would suggest to move the removing of the vbox shared folders too.

**Comment by brikis98** [comment]
Sure, that would be great. Probably the right fix is to move the `init_boot2docker` function in [setup.sh](https://github.com/brikis98/docker-osx-dev/blob/master/src/setup.sh#L393), plus the functions it calls, into the `docker-osx-dev` script.

**Comment by Simperfit** [comment]
PR send :-)

**Comment by tuanmh** [comment]
Confirmed the bug and would love to hear the PR getting merged soon :-) BTW, @brikis98, this tool does work like charm, thank you for all your effort put into this.

**Comment by brikis98** [comment]
@tuanmh: Great to hear the script is working for you. I'm just waiting on a response from @Simperfit in #36, and then it'll be ready to merge.

**Comment by brikis98** [comment]
I believe #36, which is now merged in, fixes this issue.
