### ISSUE TITLE
rsync not stable

### ISSUE THREAD

**Issue by wanghaisheng** [brikis98/docker-osx-dev#37]
i am using zsh and have added rsync plugin in .zshrc file.
rsync can work sometime ,but sometimes errors are as follows:

```
➜ /Users/wanghaisheng/workspace/docker-images/mobileapi git:(master) ✗>docker-osx-dev 
Log level: INFO
[INFO] Using default sync paths: .
[INFO] Paths to sync: /Users/wanghaisheng/workspace/docker-images/mobileapi
[INFO] Using default exclude paths: .git
[INFO] Paths to exclude: .git
[INFO] Performing initial sync of paths: /Users/wanghaisheng/workspace/docker-images/mobileapi
[INFO] sh: rsync: not found
[INFO] rsync: connection unexpectedly closed (0 bytes received so far) [sender]
[INFO] rsync error: remote command not found (code 127) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
[INFO] Initial sync done
[INFO] Watching: /Users/wanghaisheng/workspace/docker-images/mobileapi
```

**Comment by brikis98** [comment]
Are you seeing those errors by any chance after a reboot? If so, see #35 and #36. If not, can you provide a little more detail?

**Comment by wanghaisheng** [comment]
i install docker-osx-dev this evening, and since then i only boot2docker down  and up again once.

**Comment by brikis98** [comment]
Yea, it sounds like the same issue. Boot2Docker loses the rsync install and VirtualBox settings in between restarts. The PR in #36 should fix it, just waiting on one question to be answered before merging it in.

**Comment by wanghaisheng** [comment]
THX very much. do i need to reinstall using setup.sh from the scratch ?

**Comment by brikis98** [comment]
The `setup.sh` script is idempotent, so if you re-run it, it'll only install missing pieces. In fact, while waiting for #36 to be merged, you could re-run the `setup.sh` script and it'll temporarily fix your Boot2Docker image.

**Comment by wanghaisheng** [comment]
got it
