### ISSUE TITLE
Initial Rsync does not rsync all folders in docker-compose

### ISSUE THREAD

**Issue by Simperfit** [brikis98/docker-osx-dev#38]
The initial sync sync just the first folder when running the docker-osx-dev commend : 
[INFO] Performing initial sync of paths: /Users/hamza/typo3conf /Users/hamza//uploads /Users/hamza/fileadmin

[DEBUG] /Users/hamza/typo3conf /Users/hamza/uploads /Users/fileadmin :
The log_debug i added with   log_debug "$path" (in sync Line 227)

[DEBUG] rsync --archive --verbose --delete --omit-dir-times --inplace --whole-file --exclude .git --rsh="ssh -i /Users/hamza/.ssh/id_boot2docker -o StrictHostKeyChecking=no" /Users/hamza/typo3conf docker@dockerhost:/Users/hamza/projet/uccife62/uccife

output sync

[INFO] Initial sync done

[INFO] Watching: ....

(I will try to correct it)

**Comment by brikis98** [comment]
Not sure I'm following. Are you saying that you have a couple volumes in your `docker-comopse.yml` file, say volume A and B, and it's only syncing volume A?

**Comment by Simperfit** [comment]
At the initial sync : I have 3 folders to sync 

[DEBUG] /Users/hamza/typo3conf /Users/hamza/uploads /Users/fileadmin :
The log_debug i added with log_debug "$path" (in sync Line 227)

But it just sync the /Users/hamza/typo3conf.

Then, when i modify the a file in fileadmin or in uploads, it will sync it.

**Comment by Simperfit** [comment]
The PR does sync all folder specified in the docker-compose files.

**Comment by brikis98** [comment]
I'm still a bit confused on what's causing the bug and how #38 fixes it.

**Comment by brikis98** [comment]
I was able to repro this. Still trying to understand why it's happening before I merge your PR though :)

**Comment by brikis98** [comment]
Ah, figured it out. I wasn't parsing the array correctly.
