### ISSUE TITLE
rsync runs out of space

### ISSUE THREAD

**Issue by ain** [brikis98/docker-osx-dev#41]
I applied #36 today and tried to run docker-osx-dev again, but got stuck with:

```
2015-06-04 15:12:48 [INFO] Using sync paths from Docker Compose file at docker-compose.yml: . ~/.ssh
2015-06-04 15:12:48 [INFO] Paths to sync: /Users/ain/projects/app /Users/ain/projects/app/~/.ssh
2015-06-04 15:12:48 [INFO] Using default exclude paths: .git
2015-06-04 15:12:48 [INFO] Paths to exclude: .git
2015-06-04 15:12:48 [INFO] Installing rsync in the Boot2Docker image
2015-06-04 15:12:48 [INFO] Performing initial sync of paths: /Users/ain/projects/app /Users/ain/projects/sennheiser/~/.ssh
2015-06-04 15:12:49 [INFO] Syncing app/frontend/log/development.log: <f.stp......
2015-06-04 15:12:49 [INFO] rsync: [sender] write error: Broken pipe (32)
2015-06-04 15:12:49 [INFO] rsync: write failed on "/Users/ain/projects/app/frontend/log/development.log": No space left on device (28)
```

```
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G      1.8G         0 100% /
tmpfs                  1002.1M    584.0K   1001.5M   0% /dev/shm
/dev/sda1                18.2G      9.9G      7.3G  58% /mnt/sda1
cgroup                 1002.1M         0   1002.1M   0% /sys/fs/cgroup
/dev/sda1                18.2G      9.9G      7.3G  58% /mnt/sda1/var/lib/docker/aufs
/dev/loop0               28.0K     28.0K         0 100% /mnt/sda1/tmp/tcloop/popt
/dev/loop1              180.0K    180.0K         0 100% /mnt/sda1/tmp/tcloop/rsync
none                     18.2G      9.9G      7.3G  58% /mnt/sda1/var/lib/docker/aufs/mnt/1e839836a117350eeec30f7d0d3022e308c73b79acc2e2d6173f2be52dca58ad
none                     18.2G      9.9G      7.3G  58% /mnt/sda1/var/lib/docker/aufs/mnt/6ce47e2330ae920aaffe6e70ef019360cdecbfa8cf44593f6f1f247313efa2d5
none                     18.2G      9.9G      7.3G  58% /mnt/sda1/var/lib/docker/aufs/mnt/62d6747418cc4580bae58191c8815670cdebc0beb8a6ca62205b1002f3c12761
```

Any ideas on how to prevent this?

**Comment by ain** [comment]
The log was over 1 GB and ran out of that 1,8 GB allowance. Closing.

**Comment by improved-broccoli** [comment]
And what if we need more than 1.8GB? For example, my development database is more than 2GB.
I tried to resize `tmpfs` from the inside of `b2d` iso, but it did not work :/

**Comment by Simperfit** [comment]
@jbenoit2011 

You have to do something like this : 

nymeria:~$ cat ~/.boot2docker/profile 
 # boot2docker profile filename: /Users/hamza/.boot2docker/profile

Init = false
Verbose = false
Driver = "virtualbox"
Clobber = true
ForceUpgradeDownload = false
SSH = "ssh"
SSHGen = "ssh-keygen"
SSHKey = "/Users/hamza/.ssh/id_boot2docker"
VM = "boot2docker-vm"
Dir = "/Users/hamza/.boot2docker"
ISOURL = "https://api.github.com/repos/boot2docker/boot2docker/releases"
ISO = "/Users/hamza/.boot2docker/boot2docker.iso"
DiskSize = 20000
Memory = 4096
CPUs = 8
SSHPort = 2022
DockerPort = 0
HostIP = "192.168.59.3"
DHCPIP = "192.168.59.99"
NetMask = [255, 255, 255, 0]
LowerIP = "192.168.59.104"
UpperIP = "192.168.59.104"
DHCPEnabled = true
Serial = false
SerialFile = "/Users/hamza/.boot2docker/boot2docker-vm.sock"
Waittime = 300
Retries = 75

edit the Memory part( for the next time you destroy / init the vm)

Or add directly some RAM in virtualbox then reboot the VM.
tmpfs is in RAM.

**Comment by improved-broccoli** [comment]
That was obvious, I'm so dumb sometimes ...
But it works great. Thank you!

**Comment by ain** [comment]
I didn't actually want to reserve lots of space for it, but thanks for commenting :)
