### ISSUE TITLE
Failed to resolve path with tilde in docker-compose.yml

### ISSUE THREAD

**Issue by improved-broccoli** [brikis98/docker-osx-dev#42]
When I run `docker-osx-dev` in a folder where there is a `docker-compose.yml`, it failed to resolve path using the tilde, such as `~/app/data`.

It tries to resolve `/Users/foobar/~/app/data` instead of `/Users/foobar/app/data`.

Here is the error I got:

``` shell
2015-06-08 11:21:56 [INFO] rsync: link_stat "/Users/foobar/app/~/var/www" failed: No such file or directory (2)
2015-06-08 11:21:56 [INFO] rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
```

**Comment by Simperfit** [comment]
Hi @jbenoit2011,

Are you running docker-osx-dev in /Users/foobar/ ?

**Comment by improved-broccoli** [comment]
I updated my first comment.
I ran `docker-osx-dev` in `~/app`. A `docker-compose.yml` is present inside this folder.
`docker-osx-dev` just concatenate the result of `pwd` with the volume path as declared in the `docker-compose.yml`. It did not replace tilde by home dir path.

**Comment by Simperfit** [comment]
Todo, add parsing in order to eval the tilde in docker-compose.yml

**Comment by brikis98** [comment]
Should be fixed now. Give it a shot.

**Comment by brikis98** [comment]
(Of course, you need to download the new `docker-osx-dev` script into `/usr/local/bin` as described in the README)

**Comment by improved-broccoli** [comment]
Works for me with the new version. Thank you for the quick fix :+1:
