### ISSUE TITLE
Installation failed without shutting down boot2docker-vm

### ISSUE THREAD

**Issue by chouclee** [brikis98/docker-osx-dev#44]
Nice work! It's about almost the same speed to deploy Tomcat on a local directory.
But I met a problem when I was installing docker-osx-dev.  My boot2docker-vm was running at that time and I didn't notice it. Below is my message I got:

==> Installing fig dependency: docker
==> Downloading https://homebrew.bintray.com/bottles/docker-1.6.2.yosemite.bottl
###### ################################################################## 100.0%

==> Pouring docker-1.6.2.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/docker
Target /usr/local/bin/docker
already exists. You may want to remove it:
  rm '/usr/local/bin/docker'

To force the link and overwrite all conflicting files:
  brew link --overwrite docker

To list all files that would be deleted:
  brew link --overwrite --dry-run docker

Possible conflicting files are:
/usr/local/bin/docker
==> Summary
🍺  /usr/local/Cellar/docker/1.6.2: 9 files, 7.3M
==> Installing fig dependency: boot2docker
==> Downloading https://homebrew.bintray.com/bottles/boot2docker-1.6.2.yosemite.
###### ################################################################## 100.0%

==> Pouring boot2docker-1.6.2.yosemite.bottle.tar.gz
==> Caveats
To have launchd start boot2docker at login:
    ln -sfv /usr/local/opt/boot2docker/*.plist ~/Library/LaunchAgents
Then to load boot2docker now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/boot2docker
Target /usr/local/bin/boot2docker
already exists. You may want to remove it:
  rm '/usr/local/bin/boot2docker'

To force the link and overwrite all conflicting files:
  brew link --overwrite boot2docker

To list all files that would be deleted:
  brew link --overwrite --dry-run boot2docker

Possible conflicting files are:
/usr/local/bin/boot2docker
==> Summary
🍺  /usr/local/Cellar/boot2docker/1.6.2: 3 files, 7.3M
==> Installing fig
==> Downloading https://homebrew.bintray.com/bottles/fig-1.2.0.yosemite.bottle.t
###### ################################################################## 100.0%

==> Pouring fig-1.2.0.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/fig/1.2.0: 212 files, 2.7M

It's my first time to use this script so I guess it was installed. 
I used the command docker-osx-dev within the folder I want to share. I got

2015-06-08 09:40:50 [INFO] Using default sync paths: .
/usr/local/bin/docker-osx-dev: line 842: greadlink: command not found

Obviously, some dependencies are not installed properly. I think it must be related to the error message before. So I re-installed docker-osx-dev. All problem are solved.

So my opinion is, shouldn't we warn people to shut down boot2docker-vm before installing docker-osx-dev in README.md?

**Comment by brikis98** [comment]
It's strange that it tried to install it at all if you already had it installed. Before installing XXX, the installation code should be using `brew list XXX` and `type XXX` to check if it's already installed (see [here](https://github.com/brikis98/docker-osx-dev/blob/master/src/docker-osx-dev#L547)). Perhaps there is a bug in those checks?

**Comment by chouclee** [comment]
I'll check it. I would uninstall all pkgs and try to re-produce this error.

**Comment by chouclee** [comment]
Yes, I can reproduce the problem in my mac.
Here's the full log:

2015-06-08 11:44:16 [INFO] Starting install of docker-osx-dev
2015-06-08 11:44:16 [INFO] Updating HomeBrew
Already up-to-date.
2015-06-08 11:44:24 [INFO] Installing Cask
==> Installing brew-cask from caskroom/homebrew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Updating /Library/Caches/Homebrew/brew-cask--git
==> Checking out tag v0.54.0
🍺  /usr/local/Cellar/brew-cask/0.54.0: 2634 files, 10M, built in 2 seconds
2015-06-08 11:44:27 [WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
2015-06-08 11:44:27 [WARN] Found command boot2docker, assuming Boot2Docker is already installed and skipping
2015-06-08 11:44:27 [INFO] Installing Docker Compose
==> Installing dependencies for fig: libyaml, docker, boot2docker
==> Installing fig dependency: libyaml
==> Downloading https://homebrew.bintray.com/bottles/libyaml-0.1.6_1.yosemite.bo
Already downloaded: /Library/Caches/Homebrew/libyaml-0.1.6_1.yosemite.bottle.tar.gz
==> Pouring libyaml-0.1.6_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libyaml/0.1.6_1: 7 files, 352K
==> Installing fig dependency: docker
==> Downloading https://homebrew.bintray.com/bottles/docker-1.6.2.yosemite.bottl
Already downloaded: /Library/Caches/Homebrew/docker-1.6.2.yosemite.bottle.tar.gz
==> Pouring docker-1.6.2.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/docker
Target /usr/local/bin/docker
already exists. You may want to remove it:
  rm '/usr/local/bin/docker'

To force the link and overwrite all conflicting files:
  brew link --overwrite docker

To list all files that would be deleted:
  brew link --overwrite --dry-run docker

Possible conflicting files are:
/usr/local/bin/docker
==> Summary
🍺  /usr/local/Cellar/docker/1.6.2: 9 files, 7.3M
==> Installing fig dependency: boot2docker
==> Downloading https://homebrew.bintray.com/bottles/boot2docker-1.6.2.yosemite.
Already downloaded: /Library/Caches/Homebrew/boot2docker-1.6.2.yosemite.bottle.tar.gz
==> Pouring boot2docker-1.6.2.yosemite.bottle.tar.gz
==> Caveats
To have launchd start boot2docker at login:
    ln -sfv /usr/local/opt/boot2docker/*.plist ~/Library/LaunchAgents
Then to load boot2docker now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.boot2docker.plist
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/boot2docker
Target /usr/local/bin/boot2docker
already exists. You may want to remove it:
  rm '/usr/local/bin/boot2docker'

To force the link and overwrite all conflicting files:
  brew link --overwrite boot2docker

To list all files that would be deleted:
  brew link --overwrite --dry-run boot2docker

Possible conflicting files are:
/usr/local/bin/boot2docker
==> Summary
🍺  /usr/local/Cellar/boot2docker/1.6.2: 3 files, 7.3M
==> Installing fig
==> Downloading https://homebrew.bintray.com/bottles/fig-1.2.0.yosemite.bottle.t
Already downloaded: /Library/Caches/Homebrew/fig-1.2.0.yosemite.bottle.tar.gz
==> Pouring fig-1.2.0.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/fig/1.2.0: 212 files, 2.7M

**Comment by chouclee** [comment]
And actually shutting down boot2docker-vm doesn't help to prevent this error. 
Re-install docker-osx-dev could solve the problem.

I think "eval "$brew_command list $package_name" > /dev/null 2>&1 ; then" didn't work because "docker" was installed as a dependency for "fig". This is judged by brew itself not by your code.

BTW, "brew ls" will not show "docker" & "boot2docker" packages if I installed them manually without using brew. I think that's why brew thought they were not installed.

**Comment by chouclee** [comment]
I think "eval "$brew_command list $package_name" > /dev/null 2>&1 ; then" didn't work is because "docker" was installed as a dependency for "fig". This is judged by brew itself not by your code.

BTW, "brew ls" will not show "docker" & "boot2docker" package if I installed them manually without using brew. I think that's why brew thought they were not installed.

**Comment by brikis98** [comment]
But even if brew doesn't list them as installed, don't they still show up on your path if you type in the `docker` or `boot2docker` commands? If so, why didn't the `type` check find them?

**Comment by chouclee** [comment]
yes, they still show up if I type docker & boot2docker after uninstalling all brew packages. I think brew failed to find them, not your code.

**Comment by brikis98** [comment]
I've added an explicit check after `brew install` to see if things installed correctly. If they don't, the install script will complain loudly, hopefully making these sorts of issues easier to debug.
