### ISSUE TITLE
nodemon not restarting although rsync is working

### ISSUE THREAD

**Issue by jonahlau** [brikis98/docker-osx-dev#45]
Hi, rsync is working perfectly and I can confirm that changes made on the local volume are being reflected in the docker container's source code by using `docker exec` and entering the container. 

However, I'm using nodemon to watch for changes and it isn't triggering a server restart even though the files being watched have changed? 

Any help would be much appreciated, thanks!

**Comment by brikis98** [comment]
Could you:
1. Run nodemon with the verbose flag and see if that makes the issue easier to identify.
2. Connect to the container and make a change in it yourself instead of using rsync and see if that triggers a nodemon restart.

**Comment by jonahlau** [comment]
Really sorry, I noobed out and actually forgot to set WORKDIR in the dockerfile so nodemon was actually watching the wrong directory the whole time.  Everything works great.  I'll close this issue now.
