### ISSUE TITLE
Umount instead of shared folder removal

### ISSUE THREAD

**Issue by ghost** [brikis98/docker-osx-dev#49]
Hey Ho,

first to say: Thanks a bunch for making docker development on osx possible.
Now it is fast and makes a lot of fun! Without rsync it was not useable...

I glanced through the code a bit. Is it really necessary to remove the VirtualBox Share through restarting the box? Wouldn't it be enough to umount the share (e.g.: boot2docker ssh sudo umount /Users)? After that the rsync would be on the virtual hard disk of the machine and should not slow down the file sync anymore.

Should I prepare a Pull Request or did i omit a fact?

Greetings, @it_supertramp

**Comment by brikis98** [comment]
Good question. To be honest, I'm not sure what the effect would be on performance, so to be extra sure we weren't dealing with VirtualBox Shares, I just removed them. However, it's possible `umount` would be enough. Do you want to try it out? Perhaps measure the build time for some reasonably complicated project with VirtualBox shares enabled, disabled, and `umount` and see what numbers you get?

**Comment by ghost** [comment]
Cool - I'll try it out this evening with a rails project which was incredible slow with vboxfs.

**Comment by ghost** [comment]
Couldn't recreate something useful for testing - which is shareable.
I'll have to delay it till weekend.

**Comment by ghost** [comment]
Okay tested it. Speed does not change. I tested it with
https://github.com/railstutorial/sample_app_rails_4
and some scripts from
https://robots.thoughtbot.com/rails-on-docker
This is the summary:

I tested with the following (instead of removal i used a umount)

<pre>
 342           #remove_shared_folders "$vm_name" "$vbox_shared_folders"
 343           boot2docker ssh sudo umount /Users
</pre>

Greetings, Thomas

https://github.com/tsupertramp/vboxfs-slow-rails-issue

**Comment by brikis98** [comment]
Nice. In that case, I'm more than happy to merge in a PR that uses `umount` instead of removing the shares. Thanks!
