### ISSUE TITLE
Support docker-machine

### ISSUE THREAD

**Issue by ilkka** [brikis98/docker-osx-dev#50]
Hi, how would you feel about a PR adding support for docker-machine? A few simple hacks made it work for me, and I'm pretty sure accommodating both options would be possible. If it's something you would like to see, I could try to come up with a reasonable PR.

**Comment by brikis98** [comment]
Do you mean using docker-machine to install docker/boot2docker instead of using HomeBrew to do it? Or is there some way to add a custom docker-machine "recipe" that would install docker-osx-dev itself?

**Comment by ilkka** [comment]
I meant having docker-osx-dev optionally use the docker-machine CLI instead of boot2docker. Docker-machine's virtualbox driver uses the boot2docker ISO AFAIK but in that setup, the boot2docker binary isn't provided.

**Comment by brikis98** [comment]
Ah, gotcha. Assuming that doesn't fork the code too much, I'd be OK with a PR for that. Thanks!

**Comment by labianchin** [comment]
+1
docker-machine support would allow to use docker-osx-dev against a docker host in a cloud provider (EC2, openstack, etc).

**Comment by lhazlewood** [comment]
+1

boot2docker CLI is [deprecated](https://github.com/boot2docker/boot2docker-cli) and docker-machine is the docker team's official solution for launching VMs for docker across platforms.

**Comment by brikis98** [comment]
Thanks for the info folks. I'll be happy to merge the PR, but I'm currently on the road with limited Internet access, so it'll be a few days before I can take a proper look.

**Comment by ilkka** [comment]
Looks like @labianchin beat me to the punch, good work! That's what I get for vacationing AFK I guess :) I had some work that included supporting both b2d and Docker Machine and command line switches to choose between them, but @brikis98 I guess you're gonna drop b2d support now? If so, I'm not gonna bother to rebase my weeks old stuff :)

**Comment by ain** [comment]
I think we can close this one @brikis98? I'm running `docker-machine` right now, works.

**Comment by brikis98** [comment]
Yup, closing
