### ISSUE TITLE
Broken on boot2docker 1.7

### ISSUE THREAD

**Issue by saulshanabrook** [brikis98/docker-osx-dev#52]
Rsync won't install on the boot2docker 1.7 image, so this won't work on it (https://github.com/boot2docker/boot2docker/issues/936)

A current workaround is to manually tell boot2docker to use the earlier image.

```
docker-osx-dev install
# wait for it to install some stuff and then fail
boot2docker delete
rm -r ~/.boot2docker
boot2docker init --iso-url="https://github.com/boot2docker/boot2docker/releases/download/v1.6.2/boot2docker.iso" -v
docker-osx-dev install
```

**Comment by saulshanabrook** [comment]
It might be good to add this, or some other warning, to the readme. My friend was trying to install this yesterday and it took a while to figure out why it wasn't working. Any new user on mac trying to install now will come up against this problem, because boot2docker always downloads the newest image, even if you are using an older version of the CLI.

**Comment by brikis98** [comment]
Thanks for the heads up. I wonder what the issue is with 1.7... At any rate, we should probably add a warning and set the version the `install` command installs as 1.6.

**Comment by saulshanabrook** [comment]
Even if 1.6 is installed it will still pull in the 1.7 iso when installing. I had 1.6 installed and it still downloaded the 1.7 iso. The 1.7 isn't pulled into homebrew yet anyway (waiting on https://github.com/Homebrew/homebrew/pull/40889) so i assume most people won't have it installed yet.

**Comment by brikis98** [comment]
What is pulling in the 1.7 iso? docker-osx-dev or boot2docker itself?

**Comment by saulshanabrook** [comment]
boot2docker itself.

On Sat, Jun 20, 2015 at 2:37 PM, Yevgeniy Brikman notifications@github.com
wrote:

> What is pulling in the 1.7 iso? docker-osx-dev or boot2docker itself?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brikis98/docker-osx-dev/issues/52#issuecomment-113801112
> .

## 

Saul Shanabrook
about.me/shanabrook
[image: Saul Shanabrook on about.me]
  http://about.me/shanabrook

**Comment by leemhenson** [comment]
I just nuked my 1.6.2 setup and reinstalled:

```
docker-osx-dev install
2015-06-23 11:50:01 [INFO] Starting install of docker-osx-dev
2015-06-23 11:50:01 [INFO] Updating HomeBrew
Already up-to-date.
2015-06-23 11:50:11 [WARN] Cask is already installed by HomeBrew, skipping
2015-06-23 11:50:11 [WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
2015-06-23 11:50:12 [WARN] Boot2Docker is already installed by HomeBrew, skipping
2015-06-23 11:50:12 [WARN] Docker Compose is already installed by HomeBrew, skipping
2015-06-23 11:50:12 [WARN] fswatch is already installed by HomeBrew, skipping
2015-06-23 11:50:12 [WARN] GNU core utilities is already installed by HomeBrew, skipping
2015-06-23 11:50:12 [INFO] Initializing Boot2Docker VM
2015-06-23 11:50:19 [INFO] Starting Boot2Docker VM
Waiting for VM and Docker daemon to start...
.........................ooooooooooooooooooooooo
Started.
Writing ~/.boot2docker/certs/boot2docker-vm/ca.pem
Writing ~/.boot2docker/certs/boot2docker-vm/cert.pem
Writing ~/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

2015-06-23 11:50:57 [INFO] Installing rsync in the Boot2Docker image
Downloading: popt.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
popt.tcz: OK
popt.tcz             100% |*******************************| 28672   0:00:00 ETA
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz            100% |*******************************|   180k  0:00:00 ETA
2015-06-23 11:50:59 [WARN] /etc/hosts already contains dockerhost, will not overwrite
2015-06-23 11:50:59 [WARN] All Boot2Docker environment variables already defined, will not overwrite
2015-06-23 11:50:59 [INFO] docker-osx-dev setup has completed successfully.
2015-06-23 11:50:59 [INSTRUCTIONS] You can now start file syncing using the docker-osx-dev script and run Docker containers using docker run. Example:
     > docker-osx-dev
     > docker run -v $(pwd):/src some-docker-container
```

My files are rsyncing ok so I perhaps this bug was fixed upstream?

**Comment by leemhenson** [comment]
oooh, or has this succeeded because I already have a `~/.boot2docker/boot2docker.iso` which is presumably the 1.6.2 image?

**Comment by Simperfit** [comment]
do a boot2docker ssh and check the version

**Comment by leemhenson** [comment]
Yep, my bad:

```
$ boot2docker ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.6.2, build master : 4534e65 - Wed May 13 21:24:28 UTC 2015
Docker version 1.6.2, build 7c8fca2
```

**Comment by leemhenson** [comment]
So this is now broken because `getBuild` in `/etc/init.d/tc-functions` now returns `x86_64` rather than `x86`. As a result, `tce-load` tries to grab `rsync.tcz` from `http://repo.tinycorelinux.net/6.x/x86_64/tcz/` rather than `http://repo.tinycorelinux.net/6.x/x86/tcz/`. That directory doesn't contain `rsync.tcz`. You can run:

`sudo sed -i 's/echo \"x86_64\"/echo \"x86\"/' /etc/init.d/tc-functions`

And then `tce-load -wi rsync` succeeds, but I don't know if that will break anything else.

**Comment by brikis98** [comment]
@leemhenson Perhaps a better fix, at least for now, is to have the `install` command hard-code an older version of the boot2docker iso image when it runs the `boot2docker init` command?

**Comment by thieman** [comment]
I worked around this by compiling an `rsync` binary on 64-bit Ubuntu and running it in my Tiny Linux VM. You could either do the same or download mine here if you're so inclined: https://64bit-rsync.s3.amazonaws.com/rsync

**Comment by brikis98** [comment]
Hey folks, is this still an issue for you? I just uninstalled docker/boot2docker, used `docker-osx-dev install` to reinstall everything (which included docker 1.7), and rsync installed just fine.

**Comment by saulshanabrook** [comment]
@brikis98 Just tried again, and it still seemed to break...

```
$ docker-osx-dev install
2015-06-26 09:16:50 [INFO] Starting install of docker-osx-dev
2015-06-26 09:16:50 [INFO] Updating HomeBrew
Already up-to-date.
2015-06-26 09:17:03 [WARN] Cask is already installed by HomeBrew, skipping
2015-06-26 09:17:04 [WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
2015-06-26 09:17:04 [WARN] Boot2Docker is already installed by HomeBrew, skipping
2015-06-26 09:17:04 [WARN] Found command docker-compose, assuming Docker Compose is already installed and skipping
2015-06-26 09:17:04 [WARN] fswatch is already installed by HomeBrew, skipping
2015-06-26 09:17:05 [WARN] GNU core utilities is already installed by HomeBrew, skipping
2015-06-26 09:17:05 [INFO] Installing rsync in the Boot2Docker image
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: server returned error: HTTP/1.1 404 Not Found
Error on rsync.tcz
md5sum: rsync.tcz.md5.txt: No such file or directory
error in run: exit status 1
$ boot2docker version
Boot2Docker-cli version: v1.7.0
$ brew upgrade
$ 
```

**Comment by saulshanabrook** [comment]
I realized I didn't delete the boot2docker image first, but even after doing that (`boot2docker delete`), it still fails:

```
$ docker-osx-dev install
2015-06-26 09:39:04 [INFO] Starting install of docker-osx-dev
2015-06-26 09:39:04 [INFO] Updating HomeBrew
Already up-to-date.
2015-06-26 09:39:16 [WARN] Cask is already installed by HomeBrew, skipping
2015-06-26 09:39:16 [WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
2015-06-26 09:39:16 [WARN] Boot2Docker is already installed by HomeBrew, skipping
2015-06-26 09:39:17 [WARN] Found command docker-compose, assuming Docker Compose is already installed and skipping
2015-06-26 09:39:17 [WARN] fswatch is already installed by HomeBrew, skipping
2015-06-26 09:39:17 [WARN] GNU core utilities is already installed by HomeBrew, skipping
2015-06-26 09:39:17 [INFO] Initializing Boot2Docker VM
Latest release for github.com/boot2docker/boot2docker is v1.7.0
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.7.0/boot2docker.iso
    to /Users/saul/.boot2docker/boot2docker.iso
2015-06-26 09:40:09 [INFO] Starting Boot2Docker VM
Waiting for VM and Docker daemon to start...
............................oooooooooooooooooooo
Started.
Writing /Users/saul/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/saul/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/saul/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

2015-06-26 09:40:47 [INFO] Installing rsync in the Boot2Docker image
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: server returned error: HTTP/1.1 404 Not Found
md5sum: rsync.tcz.md5.txt: No such file or directory
Error on rsync.tcz
error in run: exit status 1
```

**Comment by kramano** [comment]
Same here.

**Comment by ain** [comment]
I've also got the same problem.

Altogether, `1.7` is a disaster, it's not anywhere near stable, should be in beta. Loads of other problems, not just this. I'd cheer for no action except for solving obvious blockers until they have reached a version that can be referred to as stable.

**Comment by saulshanabrook** [comment]
FYI if you wanna make sure brew doesn't try to upgrade to 1.7 prematurely `brew pin boot2docker docker`

**Comment by brikis98** [comment]
Weird. Here's what I did:

```
boot2docker stop
boot2docker delete
brew uninstall docker boot2docker docker-compose
docker-osx-dev install
```

This installs docker 1.7 and seems to work fine on my computer (i.e. no rsync install issues).

**Comment by brikis98** [comment]
Oh wait, I think despite that it was still using the 1.6.2 iso, so now my client and server are out of sync. I'm following [these instructions](http://stackoverflow.com/questions/24586573/docker-error-client-and-server-dont-have-same-version) to try to get the new version now, but I suspect I will regret that shortly :)

**Comment by brikis98** [comment]
OK, and now I'm able to repro the rsync install bug :)

**Comment by brikis98** [comment]
Alright, as a temporary workaround (hopefully temporary...), I've copied @thieman's `rsync` binary into this repo and am now manually installing that binary instead of using `tce-load`. It seems to work for me. Update the docker-osx-dev script in your `/usr/local/bin` and give it a shot.

**Comment by ain** [comment]
Good call @brikis98, thanks :+1:

**Comment by saulshanabrook** [comment]
@brikis98 Thank you so much!

**Comment by cameronbrunner** [comment]
Don't know why a 64 bit rsync tcz isn't included in TinyCore but that is the root cause of this issue.  The 1.7.0 version of the boot2docker iso moved to 64 bit pure user space and you can see there is no 64 bit rsync package in tiny core (http://distro.ibiblio.org/tinycorelinux/6.x/x86_64/tcz/).  I am going to try and create a 64 bit rsync tcz and see if the tiny core folks are interested.

**Comment by thieman** [comment]
> I am going to try and create a 64 bit rsync tcz and see if the tiny core folks are interested.

![](http://capnaux.com/wp-content/uploads/2013/05/tumblr_lok6qzByY41qjdpg8o1_400.jpg)

**Comment by cameronbrunner** [comment]
Gotta love airplane.  So they took my contribution today and placed it on the TCL site.  Expect to see rsync in all of the TCL 64 bit mirrors soon.

http://www.tinycorelinux.net/6.x/x86_64/tcz/updates/updatelist.txt

**Comment by thieman** [comment]
@cameronbrunner Thank you!

**Comment by brikis98** [comment]
@cameronbrunner: Thanks for doing the leg work. I just tried to use `tce-load` to install rsync, and while the install completes, when I try to run rsync, I get the error:

```
rsync: error while loading shared libraries: libattr.so.1: cannot open shared object file: No such file or directory
```

Any ideas?

**Comment by cameronbrunner** [comment]
Looks like my machines all have 'attr' installed.  Please try 'tce-load -wi attr' and see if it fixes your problem.  Minimally it appears I need to add it to my dependencies.

**Comment by cameronbrunner** [comment]
Here are the libraries that I see required on my box... On a clean machine I was able to run rsync after:

tce-load -wi attr
tce-load -wi acl

I will get the deps pushed up and resubmit.

/scratch $ ldd /usr/local/bin/rsync 
    linux-vdso.so.1 (0x00007ffd3529e000)
    libattr.so.1 => /usr/local/lib/libattr.so.1 (0x00007f9c9f325000)
    libacl.so.1 => /usr/local/lib/libacl.so.1 (0x00007f9c9f11e000)
    libc.so.6 => /lib/libc.so.6 (0x00007f9c9edaf000)
    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9c9eb9e000)
    /lib/ld-linux-x86-64.so.2 (0x00007f9c9f52c000)

This is reflected in cameronbrunner/tinycorelinux-extensions#1

**Comment by brikis98** [comment]
@cameronbrunner: thanks!

**Comment by AndrewSwerlick** [comment]
A note to help those debugging this issue, if you upgrade the docker-osx-dev script, but don't upgrade boot2docker, you will still get an rsync not found issue with the latest version of the script. For whatever reason the binary does not work on 1.6.2. Make sure both are upgraded if you use the newest script.

**Comment by cameronbrunner** [comment]
Just wanted to wrap the issue with automatic dependencies up; the TCL team took the .dep file over the weekend so `tce-load -wi rsync` should now work.
