### ISSUE TITLE
What about xhyve instead of VirtualBox?

### ISSUE THREAD

**Issue by sumyuga** [brikis98/docker-osx-dev#56]

**Comment by brikis98** [comment]
I've never heard of xhyve. Does it have a similar problem as boot2docker (or, more accurately, VirtualBox) and slow file syncing?

**Comment by sumyuga** [comment]
I mean VirtualBox of course. There are few solutions around xhyve working with boot2docker and core os. I think xhyve is more interesting than VirtualBox, because of lightweight virtualization on native hypervisor framework. The performance it's not like that VirtualBox yet (xhyve IO is slower). What about file syncing I have no any tests.

**Comment by brikis98** [comment]
Well, if you want to give it a shot, I'd be curious to hear how it works for you. If it looks promising, I'd explore it further, but for the time being, I think I'd prefer to stick with the officially supported Boot2Docker.

**Comment by ain** [comment]
xhyve has been tested against vbox performance and there was up to 4x loss, so unfortunately, at this early stage of the xhyve driver, it's a no go. https://thepracticalsysadmin.com/xhyve-vs-vbox-driver-benchmarks-for-docker-machine/ or http://simonvanderveldt.nl/boot2docker-on-xhyve/

**Comment by ain** [comment]
I've now tested xhyve myself since Docker for Mac uses xhyve and does not require VirtualBox, it works with `osxfs` internally.

The result: as stated above. Much slower than on VirtualBox. Exciting development, but still slow, as expected.
