### ISSUE TITLE
DEFAULT_FOLDERS_TO_SYNC should be array

### ISSUE THREAD

**Issue by skomputer** [brikis98/docker-osx-dev#6]
After running `docker-osx-dev init` then `docker-osx-dev start` I got the following error:

```
Vagrantfile:66:in `[]': no implicit conversion of Symbol into Integer (TypeError)
```

It seems that in the generated `Vagrantfile` `DEFAULT_FOLDERS_TO_SYNC` should be an array containing a hash:

```
DEFAULT_FOLDERS_TO_SYNC = [{:src => VAGRANT_ROOT, :dest => VAGRANT_ROOT}]
```

instead of just the hash:

```
DEFAULT_FOLDERS_TO_SYNC = {:src => VAGRANT_ROOT, :dest => VAGRANT_ROOT}
```

**Comment by brikis98** [comment]
Good catch! Just fixed it. I'm having some issues with the CircleCI build, so my automated tests aren't running now, but the change is committed if you want to delete that `Vagrantfile` and try again.
