### ISSUE TITLE
rsync permission denied errors?

### ISSUE THREAD

**Issue by jamesdixon** [brikis98/docker-osx-dev#71]
Hi, 

First of all, this is a great package! I've struggled getting a suitable working environment on OSX and this has basically solved my issues. Thank you!

Second, I seem to get a ton of `Permission denied (13)` errors in the `rsync` output. I'm running `docker-osx-dev` as the same user that has permission to these files. 

Anyone else run into this?

Best,
James

**Comment by brikis98** [comment]
Can run docker-osx-dev with the `-l DEBUG` flag and post the full logging output?

**Comment by jwdeane** [comment]
@jamesdixon complete guess, but I had the same issue due to previous NFS experimentation as described here: https://github.com/boot2docker/boot2docker/issues/581#issuecomment-74535277

`boot2docker delete`, `init`, `up` and then re-running `docker-osx-dev` resolved the issue for me.

**Comment by brikis98** [comment]
I haven't heard back on this issue for a while, so closing. Please re-open if you have more info.
