### ISSUE TITLE
Invalid gitfile format

### ISSUE THREAD

**Issue by ain** [brikis98/docker-osx-dev#73]
Always, after running docker-osx-dev, I'm getting `exit code of #128 fatal: Invalid gitfile format: .git`, e.g. on Bower 

```
bower jQuery#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128 fatal: Invalid gitfile format: .git
```

I first thought it's a Docker issue (docker/docker#14594), but it isn't.

I have a suspicion that docker-osx-dev corrupts the project or that the sync is somehow incomplete. Mainly because without it, it works.

**Comment by ain** [comment]
My current solution has been to restart boot2docker.

**Comment by brikis98** [comment]
Can you post more details on what your project setup looks like, what you're running, and the docker-osx-dev log output with the `-l DEBUG` flag?

**Comment by ain** [comment]
No more reproducible on the latest version with Docker Machine support. Thanks for the updates!
