### ISSUE TITLE
What was wrong with Vagrant+Boot2Docker and rsync-auto ?

### ISSUE THREAD

**Issue by r0ssIV** [brikis98/docker-osx-dev#78]
Hi Yevgeniy,

In your blog and readme you mention that you checked blinkreaction/boot2docker-vagrant solution.
That one uses built in rsync-feature of Vagrant and "vagrant rsync-auto" command.
Could you tell what was still bad with it, as now I am trying to get docker installed on Windows (your solution if more for OSX)

**Comment by brikis98** [comment]
blinkreaction/boot2docker-vagrant worked reasonably well, so if you need Windows support, it's probably a good alternative. The main downsides were:
1. rsync was a bit spotty and slow. I don't remember the exact details, but I had to use the [vagrant gatling rsync plugin](https://github.com/smerrill/vagrant-gatling-rsync) to work around the issues.
2. Using vagrant meant you had to learn, install, and maintain yet another technology on top of docker, docker-compose, rsync, and so on. It added unnecessary complexity when all I really needed was rsync.
3. I'm not an expert on Vagrant, but it seems like you needed a separate `Vagrantfile` for each project, and therefore a separate VM for each project. I just wanted to use a single VM with the boot2docker image for all of my projects.

**Comment by r0ssIV** [comment]
Thank you for explanation. By fortune we are using Ubuntu, OSX and Windows developer machines, and trying to find some universal solution. For OSX we made the [fork](https://github.com/DataSyntax/syncd) of https://github.com/drunomics/syncd - a kind of bash script using native inotifyevents and fsevents on OSX.
But on Windows/CYGWIN was hard to adapt it, so stuck with vagrant rsync-auto. Will try gatling plugin - will be great if it uses windows native event system.

**Comment by r0ssIV** [comment]
Just a short update - I tested gatling rsync plugin and it does not work on Windows - the initial rsync is run ok, but file watching is not capturing changes. Therefore had to turn back to 'vagrant rsync-auto' on Windows.

**Comment by achekulaev** [comment]
> I'm not an expert on Vagrant, but it seems like you needed a separate Vagrantfile for each project

Nope. One Vagrantfile for all projects. One VM.
