### ISSUE TITLE
Hangs with docker-machine

### ISSUE THREAD

**Issue by pintomau** [brikis98/docker-osx-dev#83]
After creating a new docker-machine "dev" and running eval `"$(docker-machine env dev)"`, when I run `docker-osx-dev`, it hangs in the step "Installing rsync in the Docker Host image".

Then it echoes the message "exit status 1".

When I try running `docker-osx-dev` again, it hangs in "Performing initial sync of paths" until it eventually echoes the same "exit status 1" message.

@labianchin

**Comment by labianchin** [comment]
Thanks for reporting this.

Can you run in the debug mode and provide the logs? It would be like `docker-osx-dev -l DEBUG`.
Also can you try running something like `docker-machine ssh "uname -a"`. What driver and image are you using for docker-machine ?

**Comment by pintomau** [comment]
Thanks for answering!

Running with debug, I think this has to do with the problem:
`Creating parent directories in Docker VM: sudo mkdir -p /Users/me && sudo chown -R docker /Users/me`

`docker-machine ssh dev "uname -a"`:
`Linux dev 4.0.7-boot2docker #1 SMP Wed Jul 15 00:01:41 UTC 2015 x86_64 GNU/Linux`

Created the image with `docker-machine create --driver virtualbox dev`.

**Comment by crybat** [comment]
I forgot to post the full debug logs. I'll post it tomorrow, when I have access to the machine again.

**Comment by abritinthebay** [comment]
It does seem (I'm running into this atm too) that it's trying to sync on folder level up for some reason.

like `/Users/myusername/git/dockerproject/` is the actual folder but that rsync setup step is outputting:

`2015-08-11 10:48:15 [DEBUG] Creating parent directories in Docker VM: sudo mkdir -p /Users/myusername/git && sudo chown -R docker/Users/myusername/git`

**Comment by abritinthebay** [comment]
Confirmed - it was trying to sync my entire git projects directory. Clearly wrong behavior.

**Comment by abritinthebay** [comment]
I'd suggest that something is going wrong here:

```
  for path in "${paths_to_sync[@]}"; do
      local readonly parent_dir=$(dirname "$path")
      if [[ "$parent_dir" != "/" ]]; then
        dirs_to_create+=("$parent_dir")
      fi
    done
```

Because it appears to have the correct path right until then.

**Comment by abritinthebay** [comment]
It's the `dirname` - if the directory doesn't have a trailing slash it'll move it one level up.

So `dirname /Users/abritinthebay/git/myprojectdir` outputs `/Users/abritinthebay/git` which is very _very_ wrong. 

Not sure what that code is trying to do other than... for some reason... break everything ;)

**Comment by labianchin** [comment]
@crybat: it look like the rsync install on docker host is incomplete, check here: https://github.com/brikis98/docker-osx-dev/issues/84#issuecomment-130906002

**Comment by labianchin** [comment]
@abritinthebay I am not sure why `dirname` is being used this way. @brikis98, do you have any idea on this one?

**Comment by atrain0789** [comment]
I believe I am seeing an incomplete rsync installation issue as well.  When I follow the instructions in the readme to setup docker-osx-dev with docker-machine and I try to sync folders the first time I get the following:

```
[INFO] Using sync paths from Docker Compose file at docker-compose.yml: .
[INFO] Complete list of paths to sync:  /path/to/my/project
[INFO] Using default exclude paths: .git
[INFO] Complete list of paths to exclude: .git
[INFO] Complete list of paths to include: 
[INFO] Starting docker-osx-dev file syncing
[INFO] Initializing docker machine dev
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
[INFO] Installing rsync in the Docker Host image
SSH cmd error!
command: if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi
err    : exit status 1
output : rsync.tcz.dep OK
acl.tcz.dep OK
Downloading: attr.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
attr.tcz             100% |*******************************| 24576   0:00:00 ETA
attr.tcz: OK
Downloading: acl.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
acl.tcz              100% |*******************************| 40960   0:00:00 ETA
acl.tcz: OK
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz            100% |*******************************|   312k  0:00:00 ETA
rsync.tcz: OK
```

That looks like rsync isn't fully installed.  Once I run it after that, I am also getting a different issue when it is trying to sync the path seen below:

```
[INFO] Performing initial sync of paths: /path/to/my/project/
[INFO] Warning: Identity file /id_rsa not accessible: No such file or directory.
[INFO] Warning: Permanently added '192.168.99.100' (RSA) to the list of known hosts.
docker@192.168.99.100's password:
```

It is asking for the docker user's password, and even if I go in and set that, it asks for the password every time it needs to sync files.

**Comment by pintomau** [comment]
@labianchin Well, I tried installing manually, but the result was the same: hangs there.
I tried creating a new machine, this time rsync was installed successfully (although it exited with status 1), and still hangs when syncing.

**Comment by brikis98** [comment]
@labianchin, @abritinthebay: It shouldn't be trying to _sync_ the parent folders, but to _create_ them on the boot2docker VM. If you want to rsync the path `a/b/c` into the identical location on the boot2docker VM, then path `a/b` must already exist, or rsync will give you an error. Therefore, the `initial_sync` method tries to use `mkdir -p` to create all of these parent directories before starting the sync process. 

Why does creating these parent folders break things for you?

**Comment by abritinthebay** [comment]
Because it **doesn't** create them. It syncs them. That's why.

Basically it's not doing what you think it's doing. Why? Dunno, but what it ends up doing is trying to sync the entire contents of my parent directory (which in my case is every single git project I have checked out... that's a LOT of stuff).

So... that might be your intent, but it's not what it is doing. I commented this out (and tweaked the var names) and it worked fine. So clearly that _is_ the problem.

**Comment by brikis98** [comment]
@abritinthebay: Can you run docker-osx-dev with the debug flag (`-l DEBUG`) and post the command you used and the logging output?

**Comment by abritinthebay** [comment]
Sadly I've moved on to a custom rolled system that worked for me (rsync based, like yours) so I can't run it now.

However I ran everything with the `-l DEBUG` flag before and didn't see anything pop up that was particularly different to without - it just got the right folder... then truncated it to the parent... then created it... then tried to _sync_ it (rather than the original, correct, folder).

The commands were pretty self explainatory tbh.

**Comment by brikis98** [comment]
Well, it's hard to debug without more info, so if you have a chance to use it again, please post your commands and output.

**Comment by abritinthebay** [comment]
Will do - but honestly I don't think that output would help you. I was debugging it myself with that flag and it basically output nothing of use - I ended up having to step through the code anyhow.

Like I said - once I removed that `dirname` call... it all worked fine (I switched due to other perf issues). So that's clearly the problem code (or at least causing the problem symptom)
