### ISSUE TITLE
Install Script needs updating to do "brew install coreutils" and "brew install fswatch"

### ISSUE THREAD

**Issue by abritinthebay** [brikis98/docker-osx-dev#84]
Here's my debug output.

It doesn't know what paths to sync - even after finding them in the docker-compose.yml - as it can't run `greadlink`.

```
2015-08-11 10:43:31 [INFO] Using sync paths from Docker Compose file at docker-compose.yml: breport
/usr/local/bin/docker-osx-dev: line 938: greadlink: command not found
2015-08-11 10:43:31 [INFO] Complete list of paths to sync: 
2015-08-11 10:43:31 [INFO] Using default exclude paths: .git
2015-08-11 10:43:31 [INFO] Complete list of paths to exclude: .git
2015-08-11 10:43:31 [INFO] Complete list of paths to include: 
2015-08-11 10:43:31 [INFO] Starting docker-osx-dev file syncing
2015-08-11 10:43:31 [INFO] Installing rsync in the Docker Host image
2015-08-11 10:43:32 [INFO] Performing initial sync of paths: 
2015-08-11 10:43:32 [DEBUG] Creating parent directories in Docker VM: sudo mkdir -p  && sudo chown -R docker 
BusyBox v1.22.1 (2014-04-04 15:16:09 UTC) multi-call binary.

Usage: mkdir [OPTIONS] DIRECTORY...

Create DIRECTORY

        -m MODE Mode
        -p  No error if exists; make parent directories as needed

error in run: exit status 1
```

**Comment by abritinthebay** [comment]
Found it - you need to run `brew install coreutils` for this to work.

I'd strongly suggest updating your install script to install that.

**Comment by abritinthebay** [comment]
Also same issue with `fswatch`

**Comment by brikis98** [comment]
Did you run `docker-osx-dev install`? It should take care of all of those dependencies.

**Comment by abritinthebay** [comment]
Yup, didn't get everything it seems. Don't know why.

**Comment by brikis98** [comment]
I'd have to see the log output from the install. Perhaps there was an error.

**Comment by abritinthebay** [comment]
I ran into a similar issue with installing rsync on the docker host - it claimed it was installed but I guess _something_ happened. I ended up using `docker-machine ssh dev` to get into the host and then just ran the same command this script does manually.

Worked then.

I think there are perhaps some errors that fail silently and so put the script in an odd state. Not sure how or why that happens though.

**Comment by labianchin** [comment]
Hey @abritinthebay, what OS are you running in the docker host?

Now, I was looking at the `install_rsync_on_docker_host` and seems it just work for boot2docker images (Tiny Core Linux): https://github.com/brikis98/docker-osx-dev/blob/master/src/docker-osx-dev#L450
That seems to be something we forgot. :/

**Comment by abritinthebay** [comment]
Nothing special I think...? Whatever is the default - I didn't play around with it much. I'm running ubuntu on my _containers_ however.

**Comment by abritinthebay** [comment]
Side note - I had much better reliability switching to rsync on my _container_ rather than the host and just port-mapping so I could directly sync that way.

Something to consider.

**Comment by brikis98** [comment]
I've added a check after running `brew install` that will hopefully make the cause of such errors clearer in the future.
