### ISSUE TITLE
TLS Error on docker push

### ISSUE THREAD

**Issue by stuartsaltzman** [brikis98/docker-osx-dev#85]
$ sudo docker push username/repoABC
Post http:///var/run/docker.sock/v1.20/images/username/repoABC/push?tag=: dial unix /var/run/docker.sock: no such file or directory.
- Are you trying to connect to a TLS-enabled daemon without TLS?
- Is your docker daemon up and running?

**Comment by brikis98** [comment]
Sounds like docker or boot2docker isn't running. Try `docker version` and `boot2docker status` commands.

**Comment by stuartsaltzman** [comment]
I get the same error when running `docker version`.

$ `docker version`
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 23:00:11 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
- Are you trying to connect to a TLS-enabled daemon without TLS?
- Is your docker daemon up and running?

`$ boot2docker status`
running

**Comment by brikis98** [comment]
Did you just install or upgrade docker? I just noticed your version is at 1.8.0, which I believe came out very recently. I've seen issues in the past where a docker upgrade causes weird connectivity issues.

**Comment by stuartsaltzman** [comment]
I used the installation instructions from docker-osx-dev (below). I did not
have docker previously installed.

curl -o /usr/local/bin/docker-osx-dev
https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/src/docker-osx-dev
chmod +x /usr/local/bin/docker-osx-dev
docker-osx-dev install

On Thu, Aug 13, 2015 at 10:43 AM, Yevgeniy Brikman <notifications@github.com

**Comment by brikis98** [comment]
Did you add the environment variables specified at the end of the `docker-osx-dev install` command?

**Comment by stuartsaltzman** [comment]
Yes, I added the environment variables specified at the end of the
docker-osx-dev install.

Here is my .bashrc file:

[ -n "$PS1" ] && source ~/.bash_profile;

# docker-osx-dev

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/username/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

Here is the output from the docker-osx-dev install:

Initialization of virtual machine "boot2docker-vm" complete.

Use `boot2docker up` to start it.

2015-08-13 07:56:06 [INFO] Starting Boot2Docker VM

Waiting for VM and Docker daemon to start...

.o

Started.

Writing /Users/username/.boot2docker/certs/boot2docker-vm/ca.pem

Writing /Users/username/.boot2docker/certs/boot2docker-vm/cert.pem

Writing /Users/username/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:

```
export DOCKER_HOST=tcp://192.168.59.103:2376

export
```

DOCKER_CERT_PATH=/Users/username/.boot2docker/certs/boot2docker-vm

```
export DOCKER_TLS_VERIFY=1
```

Or run: `eval "$(boot2docker shellinit)"`

2015-08-13 07:56:07 [INFO] Installing rsync in the Docker Host image

2015-08-13 07:56:08 [INFO] Adding dockerhost entry to /etc/hosts so you can
use http://dockerhost URLs for testing

2015-08-13 07:56:08 [INSTRUCTIONS] Modifying /etc/hosts requires sudo
privileges, please enter your password.

2015-08-13 07:56:08 [INFO] Adding new environment variables to
/Users/username/.bashrc:

# docker-osx-dev

export DOCKER_HOST=tcp://192.168.59.103:2376

export DOCKER_CERT_PATH=/Users/username/.boot2docker/certs/boot2docker-vm

export DOCKER_TLS_VERIFY=1

2015-08-13 07:56:08 [INSTRUCTIONS] To pick up important new environment
variables in the current shell, run:

source /Users/username/.bashrc

2015-08-13 07:56:08 [INFO] docker-osx-dev setup has completed successfully.

2015-08-13 07:56:08 [INSTRUCTIONS] You can now start file syncing using the
docker-osx-dev script and run Docker containers using docker run. Example:

> docker-osx-dev
> 
> docker run -v $(pwd):/src some-docker-container

On Thu, Aug 13, 2015 at 11:38 AM, Yevgeniy Brikman <notifications@github.com

**Comment by brikis98** [comment]
The variables are in your `.bashrc` file, but did you actually `source` them before running `docker-osx-dev`?

**Comment by stuartsaltzman** [comment]
Yes, I sourced prior to running docker-osx-dev.

On Thu, Aug 13, 2015 at 11:58 AM, Yevgeniy Brikman <notifications@github.com

**Comment by brikis98** [comment]
Hm, odd. I wonder if somehow docker failed to start? Try to run `boot2docker ssh` to connect to the boot2docker VM and then run `ps aux | grep docker`.

**Comment by stuartsaltzman** [comment]
This is the output. I ran the `ps aux | grep docker` command from both
within docker and from terminal.

$ boot2docker ssh

[removed docker whale image]

Boot2Docker version 1.8.1, build master : 7f12e95 - Thu Aug 13 03:24:56 UTC
2015

Docker version 1.8.1, build d12ea79

docker@boot2docker:~$

docker@boot2docker:~$ ps aux | grep docker

root      2103  0.1  1.5 570420 31856 ?        Sl   11:56   0:15
/usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://
0.0.0.0:2376 --tlsverify --tlscacert=/var/lib/boot2docker/tls/ca.pem
--tlscert=/var/lib/boot2docker/tls/server.pem
--tlskey=/var/lib/boot2docker/tls/serverkey.pem

root      4427  0.0  0.1  27688  3820 ?        Ss   16:13   0:00 sshd:
docker [priv]

docker    4429  0.0  0.1  27688  2860 ?        S    16:13   0:00 sshd:
docker@pts/0

docker    4430  0.0  0.1  11860  2096 pts/0    Ss   16:13   0:00 -sh

docker    4472  0.0  0.0  13016  1800 pts/0    R+   16:14   0:00 ps aux

docker    4473  0.0  0.0  11860   188 pts/0    R+   16:14   0:00 -sh

docker@boot2docker:~$

$ ps aux | grep docker

root            16046   1.8  2.8  3064724 477580   ??  S     7:56AM
5:04.73 /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless --comment
boot2docker-vm --startvm ace0dafd-bb6a-4cd8-9978-89b2f977c0f3 --vrde config

username  15367   1.5  5.3  3466152 885564   ??  S     7:45AM   5:45.39
/Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless --comment boot2
docker-vm --startvm 7ec43481-b7ab-4b88-84db-bda8c1e6dae6 --vrde config

username  30704   0.0  0.0  2455896    556 s009  T    12:03PM   0:00.00
/bin/bash /usr/local/bin/docker-osx-dev

username  30703   0.0  0.0  2447704    660 s009  T    12:03PM   0:00.00
/bin/bash /usr/local/bin/docker-osx-dev

username  22253   0.0  0.0  2446680   1372 s009  T    12:03PM   0:00.03
/bin/bash /usr/local/bin/docker-osx-dev

username  31153   0.0  0.0  2432772    672 s011  S+   12:15PM   0:00.00
grep docker

username  31063   0.0  0.0  2463252   2972 s010  S+   12:13PM   0:00.02 ssh
-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o
UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i
/Users/username/.ssh/id_boot2docker docker@localhost

username  31061   0.0  0.0 145182872   3704 s010  S+   12:13PM   0:00.01
boot2docker ssh

On Thu, Aug 13, 2015 at 12:12 PM, Yevgeniy Brikman <notifications@github.com

**Comment by brikis98** [comment]
Seems to be running. I'm a bit stumped and am worried there was some change in version 1.8 that broke something. Backwards compatibility is not docker's strong suite :)

One more experiment: try to run `boot2docker stop` and then run `docker-osx-dev` to restart it.

BTW, what were you using `docker push` for in the first post? If you can't connect to the docker daemon, what could you possibly have to push? Or was it working before and suddenly stopped?

**Comment by stuartsaltzman** [comment]
I get an error when I run `docker-osx-dev`. At the bottom it says, `error
in run: exit status 1`. Thanks for your help, I really appreciate it!

$ boot2docker stop

$ docker-osx-dev

2015-08-13 12:34:53 [INFO] Using default sync paths: .

2015-08-13 12:34:53 [INFO] Complete list of paths to sync:
/Users/stuartsaltzman/foo/bar

2015-08-13 12:34:53 [INFO] Using default exclude paths: .git

2015-08-13 12:34:53 [INFO] Complete list of paths to exclude: .git

2015-08-13 12:34:53 [INFO] Complete list of paths to include:

2015-08-13 12:34:53 [INFO] Starting docker-osx-dev file syncing

2015-08-13 12:34:53 [INFO] Starting Boot2Docker VM

Waiting for VM and Docker daemon to start...

...............oooooooo

Started.

Writing /Users/stuartsaltzman/.boot2docker/certs/boot2docker-vm/ca.pem

Writing /Users/stuartsaltzman/.boot2docker/certs/boot2docker-vm/cert.pem

Writing /Users/stuartsaltzman/.boot2docker/certs/boot2docker-vm/key.pem

Your environment variables are already set correctly.

2015-08-13 12:35:14 [INFO] Installing rsync in the Docker Host image

rsync.tcz.dep OK

acl.tcz.dep OK

Downloading: attr.tcz

Connecting to repo.tinycorelinux.net (89.22.99.37:80)

attr.tcz             100% |*******************************| 24576   0:00:00
ETA

attr.tcz: OK

Downloading: acl.tcz

Connecting to repo.tinycorelinux.net (89.22.99.37:80)

acl.tcz              100% |*******************************| 40960   0:00:00
ETA

acl.tcz: OK

Downloading: rsync.tcz

Connecting to repo.tinycorelinux.net (89.22.99.37:80)

rsync.tcz            100% |*******************************|rsync.tcz: OK:02
ETA

   312k  0:00:00 ETA

error in run: exit status 1

On Thu, Aug 13, 2015 at 12:28 PM, Yevgeniy Brikman <notifications@github.com

**Comment by brikis98** [comment]
Hmm, well, I'm out of ideas. My best guess is that it's a docker 1.8 issue, but I'm still on 1.7.1 and am in the middle of a project, so I can't upgrade to repro and dig further.

If anyone else is using docker 1.8 and can poke around, that would be most appreciated :)

**Comment by brikis98** [comment]
For some reason, the `tce-load` command exits with an error, even if `rsync` installed correctly. I've put in a workaround to catch this. Hopefully, the script works OK now.
