### ISSUE TITLE
dockerhost requiring password on running 'docker-osx-dev'

### ISSUE THREAD

**Issue by amilajack** [brikis98/docker-osx-dev#86]
I'm not sure if this is intended behavior but when running sudo docker-osx-dev for the first time, I'm prompted to enter the password for dockerhost:

```
...
2015-08-14 15:04:18 [INFO] Warning: Permanently added 'dockerhost,192.168.59.103' (RSA) to the list of known hosts.
docker@dockerhost's password:
```

I think it's worth mentioning that I installed docker-osx-dev with sudo. Not sure if that helps.

**Comment by brikis98** [comment]
Why are you installing and running it with sudo? It might not be finding the right environment variables or home directory (with SSH keys and certs) as a result of that.

**Comment by ain** [comment]
I'm having exact same problem, not using `sudo` to run anything. Just went corrupt somehow. How can I restore the ISO on Docker Machine?
