### ISSUE TITLE
SSH cmd error! wget: bad address 'repo.tinycorelinux.net'

### ISSUE THREAD

**Issue by AriaFallah** [brikis98/docker-osx-dev#91]
I'm running docker-osx-dev on a computer running docker-machine.

The first time I did docker-osx-dev install, it didn't try to install rsync into the host image like it is now. Interestingly it also didn't install some dependencies the first time around either: fswatch and coreutils.

Anyways, this was still the first time around, and I tried to run docker-osx-dev inside a directory and I got the rsync error there.

So my first instinct was to reinstall again at which point fswatch and coreutils were actually installed, but it tried to also do the rsync host stuff the docker-osx-dev command did, which was weird because it didn't do that the first time around.

Anyways below is the full log and error. This is from running the install a third time when I had all the homebrew dependencies already.

I'm guessing something happened to the file that the install script tries to wget.

```
docker-osx-dev install
2015-08-24 20:14:12 [INFO] Starting install of docker-osx-dev
2015-08-24 20:14:12 [INFO] Updating HomeBrew
Already up-to-date.
2015-08-24 20:14:16 [WARN] Cask is already installed by HomeBrew, skipping
2015-08-24 20:14:16 [WARN] Boot2Docker is already installed by HomeBrew, skipping
2015-08-24 20:14:17 [WARN] Found command docker-compose, assuming Docker Compose is already installed and skipping
2015-08-24 20:14:17 [WARN] Found command docker-machine, assuming Docker Machine is already installed and skipping
2015-08-24 20:14:17 [WARN] fswatch is already installed by HomeBrew, skipping
2015-08-24 20:14:17 [WARN] GNU core utilities is already installed by HomeBrew, skipping
2015-08-24 20:14:17 [INFO] Initializing docker machine default
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
2015-08-24 20:14:18 [INFO] Installing rsync in the Docker Host image
SSH cmd error!
command: if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi
err    : exit status 1
output : Downloading: rsync.tcz
wget: bad address 'repo.tinycorelinux.net'
md5sum: rsync.tcz.md5.txt: No such file or directory
Error on rsync.tcz
```

**Comment by AriaFallah** [comment]
I created a new docker machine and the install script yielded this:

```
2015-08-24 20:40:52 [INFO] Installing rsync in the Docker Host image
SSH cmd error!
command: if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi
err    : exit status 1
output : rsync.tcz.dep OK
acl.tcz.dep OK
Downloading: attr.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
attr.tcz             100% |*******************************| 24576   0:00:00 ETA
attr.tcz: OK
Downloading: acl.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
acl.tcz              100% |*******************************| 40960   0:00:00 ETA
acl.tcz: OK
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz            100% |*******************************|   312k  0:00:00 ETA
rsync.tcz: OK
```

and it seems to work now. I wonder what the problem was.

**Comment by lukaso** [comment]
I'm seeing the same error from your second comment. But it does look like the error is not significant, since rsync is on the boot2docker vm.

The first error I also got when the new boot2docker vm didn't have network connectivity.

Here is what I use to get everything working so far (may or may not be complete):

```
boot2docker destroy
curl -o /usr/local/bin/docker-osx-dev https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/src/docker-osx-dev
chmod +x /usr/local/bin/docker-osx-dev
brew update
brew install docker-machine
docker-machine create --driver virtualbox b2d
eval "$(docker-machine env b2d)”
docker-machine stop b2d
VBoxManage modifyvm b2d --natdnsproxy1 on
docker-machine start b2d
eval "$(docker-machine env b2d)”
docker-osx-dev install
```

**Comment by brikis98** [comment]
> The first error I also got when the new boot2docker vm didn't have network connectivity.

Is that the normal state for a new docker-machine image? If so, wouldn't that explain why rsync wouldn't install?

**Comment by lukaso** [comment]
No, docker images should have network connectivity. In my network I have to do `VBoxManage modifyvm b2d --natdnsproxy1 on` to get networking going.

**Comment by idcrook** [comment]
I had to do this today too on OS X El Capitan (recipe @lukaso provided above).  
Didn't have boot2docker installed from homebrew prior to `docker-osx-dev` install, and kept getting SSH/rsync error.

```
$ docker-machine -v
docker-machine version 0.4.1 (HEAD)
$ docker -v
Docker version 1.8.2, build 0a8c2e3
$ boot2docker version
Boot2Docker-cli version: v1.8.0
Git commit: 9a26066
```

**Comment by clickwhit** [comment]
repo.tinycorelinux.net seems to be down. Is there an alternative url to get rsync?

*edit \* if the repo is ever down, you have to switch to a different mirror:

```
docker-machine ssh b2d
/*on the docker vm */
>> wget ftp://ftp.nluug.nl/pub/ibiblio/distributions/tinycorelinux/6.x/x86/tcz/mirrors.tcz
>> tcemirror.sh
/* select a different mirror here */
>> tce-load -wi rsync
```

**Comment by ain** [comment]
Known problem. Handled by #123.

**Comment by ain** [comment]
#123 merged, issue resolved. Please update your tool.

**Comment by sloba88** [comment]
I have tried latest version from today and I have two errors

```
2015-10-29 23:20:21 [INFO] Installing rsync in the Docker Host image
SSH cmd error!
command: if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi
err    : exit status 1
output : Downloading: rsync.tcz
wget: bad address 'repo.tinycorelinux.net'
Error on rsync.tcz
md5sum: rsync.tcz.md5.txt: No such file or directory

SSH cmd error!
command: type rsync > /dev/null 2>&1
err    : exit status 127
output : 
2015-10-29 23:21:21 [INFO] Failed to install rsync using tce-load, falling back to install rsync from pre-built binary in docker-osx-dev GitHub repo
SSH cmd error!
command: sudo wget -P /usr/local/bin https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/lib/rsync && sudo chmod +x /usr/local/bin/rsync
err    : exit status 1
output : wget: bad address 'raw.githubusercontent.com'
```

**Comment by brikis98** [comment]
```
wget: bad address 'repo.tinycorelinux.net'
...
wget: bad address 'raw.githubusercontent.com'
```

Both of these addresses work fine for me. Was there something wrong with your Internet connection? Or did you disable networking in your VM?

**Comment by sloba88** [comment]
I've restarted Docker and now it works, seems that it was one of those problems where container internet access gets "stuck"...
