### ISSUE TITLE
-i option fails with files deleted in image if not existing on host

### ISSUE THREAD

**Issue by ain** [brikis98/docker-osx-dev#99]
**Steps to reproduce**:
1. Add ignore file to `project_root/subfolder/.ignore` with files that do not exist on host:
   
   ```
   .git
   frontend/lib/assets/javascripts/*
   frontend/vendor/assets/javascripts/*
   frontend/log
   ```
2. Run 
   
   ```
    docker-osx-dev -i project_root/subfolder/.ignore
   ```
3. Add files to image at path, e.g.:
   
   ```
   frontend/vendor/assets/javascripts/bower_components/js-cookie/MIT-LICENSE.txt
   ```
4. Update watched file on host

**What happens**:

```
2015-09-02 19:25:42 [INFO] Syncing frontend/vendor/assets/javascripts/bower_components/js-cookie/MIT-LICENSE.txt: *deleting
```

**Comment by brikis98** [comment]
Can you run docker-osx-dev with the `-l DEBUG` flag and paste the output? The list of files to ignore should just be passed directly to rsync, so perhaps something is getting mangled along the way.

**Comment by ain** [comment]
Ignore file path was out of sync, `docker-osx-dev` got executed a level up. Could be a good ground to throw up if ignore file isn't there at the path. Otherwise it could possibly kill files unintended as it did in my case.
